spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: pass
    platform: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: mysql    
#      properties:
#        javax:
#          persistence:
#            schema-generation:
#              create-source: metadata
#              scripts:
#                action: create
#                create-target: database_create.sql
